Commenting out blocks on offline cross validation for segmentation models
When I remove lines 290, 342, and 343 from run_ml.py,  i.e. when I remove the blocks on offline cross validation
for segmentation models, then I hit the error:
	'NoneType' object has no attribute 'number_of_cross_validation_splits'
because in line 305, in spawn_offline_cross_val_classification_child_runs:
	for i in range(self.innereye_config.number_of_cross_validation_splits):
self.innereye_config is None